api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: true
      targetPort: 80
      transport: http
      allowInsecure: false
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
  template:
    containers:
      - image: {{ .Image }}
        name: healthchecksui
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: HealthChecksUI__HealthChecks__0__Name
            value: apiservice
          - name: HealthChecksUI__HealthChecks__0__Uri
            value: http://apiservice:8081/healthz
          - name: HealthChecksUI__HealthChecks__1__Name
            value: webfrontend
          - name: HealthChecksUI__HealthChecks__1__Uri
            value: http://webfrontend:8081/healthz
          - name: ui_path
            value: /
    scale:
      minReplicas: 1
tags:
  azd-service-name: healthchecksui
  aspire-resource-name: healthchecksui
